butttonpoll setup timeout
Vexed01/Vex-Cogs pull request #113
Opened 2023-05-09 19:21 UTC by fakesmile723

Changed buttonpoll timeout from **3 mins** to **5 mins**.
Not much as this is my first PR ever in git

2023-05-09 19:28 UTC, Vexed01 requested changes

2023-05-09 20:14 UTC, fakesmile723 commented on buttonpoll/components/setup.py
Ohh i didnt think that far. Thanks for pointint out.

2023-05-15 15:07 UTC, Vexed01 approved these changes

2023-05-15 15:07 UTC, Vexed01 commented
Thanks for taking the time to make a PR!

2023-05-15 15:07 UTC, merged